site_name: Blockbench
theme: readthedocs
nav:
  - Home: index.md
  - Plugin: plugin.md
  - Blockbench: blockbench.md
  - Interface: ui.md
  - Undo: undo.md
  - Utility: utility.md
  - Formats: formats.md
  - Textures: textures.md