site_name: Blockbench
theme: readthedocs
nav:
  - Getting Started: index.md
  - Plugin: plugin.md
  - Blockbench: blockbench.md
  - Interface: ui.md
  - Formats: formats.md
  - Actions: actions.md
  - Menu: menu.md
  - Undo: undo.md
  - Modes: modes.md
  - Outliner: outliner.md
  - Textures: textures.md
  - Preview: preview.md
  - Utility: utility.md
  - Theme: theme.md